### ISSUE TITLE
Create Azure File Share

### ISSUE THREAD

**Issue by basplijnaer** [AmpersandTarski/RAP#174]
To use volumes in Azure, Azure Files shares have to be used.

**Tasks**

- [x] Create storage account
- [x] Create file share
- [x] Update docker compose file with file share
