### ISSUE TITLE
Epic: Implement CI/CD

### ISSUE THREAD

**Issue by FreekOrdina** [AmpersandTarski/RAP#229]
To automate the deployment of RAP, we must implement continuous integration / continuous deployment pipelines of RAP into the Kubernetes Clusters of Ordina and OU. The purpose of this is to accelerate the time to deploy and allow more frequent deployments. The condition is that the workflow must be easily maintainable.

Tasks:
- [x] Implement minimal CICD workflow
- [x] Extend workflow with multiple stages 
- [x] Provide environments for different stages
- [x] Optional (?) Create AKS cluster from workflow
- [x] Optional (?) Create AKS manifests from workflow
- [x] Deploy AKS manifests to AKS cluster
- [x] Document for maintainability.

**Comment by stefjoosten** [comment]
@FranSlot: Can you verify which documentation for maintainability we still need? (Otherwise, check the box and close the issue)
