### ISSUE TITLE
Update RAP4 source code to create student-prototype Pod

### ISSUE THREAD

**Issue by FreekOrdina** [AmpersandTarski/RAP#234]
**Purpose**
Prepare RAP4 application to be used in a Kubernetes cluster.

**Subtasks**
- [x] Find documentation on how to create a new Pod from a running Pod in Kubernetes
- [x] Check if we can update the code such that it works both for Docker-compose and Kubernetes
- [x] Update .\RAP4\customizations\bootstrap\files\ExecEngineFunctions.php
- [x] Create pull request
- [ ] Update image on Docker hub

When finished a new RAP4 docker image should be ready to be used in Kubernetes

**Comment by stefjoosten** [comment]
# Complicatie
Het starten van een studenten prototype container moet gebeuren middels het aanroepen van de Kubernetes API, in plaats van de huidige aanroep van de docker-daemon.
De pod moet dus ook de juiste credentials hebben zodat de RAP-applicatie de juiste API-call in het Kubernetes cluster mag doen.

**Comment by Michiel-s** [comment]
Issue marked done
