### ISSUE TITLE
Add RAP4 to Kubernetes cluster

### ISSUE THREAD

**Issue by FreekOrdina** [AmpersandTarski/RAP#235]
**Purpose**
Finalize RAP4 deployment. Making sure that the functionality of the deployment is equal to the deployment using Docker Compose.

**Subtasks**
Add RAP4 to Kubernetes cluster and make it work.

- [x] Add RAP4 to Kubernetes cluster
- [x] Configure ingress controller to make RAP4 accessible
- [x] Check if adding a student-prototype works.

When finished we should be able to access phpmyadmin by something like:
https://rap4.ampersand-rap.azurewebsites.net/

**Comment by Michiel-s** [comment]
Issue marked done
