### ISSUE TITLE
Replace RAP by a VS-code devcontainer

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#238]
# Problem
The RAP application can be seen as an IDE for Ampersand. We spend effort to maintain it. However, today IDE's have been replaced by VS-code tuned to specific languages. That seems the way to go ahead because it allows us to reuse code (i.e. an editor for Ampersand) and save some duplicate functionality (i.e. syntax colouring, the ACE editor).

# Analysis
By the looks of it, the functionality of RAP can be realised within VS-code. By wrapping it in a dev-container, we can ship it as a simple-to-install IDE for Ampersand. This analysis is yet to be done.

# Proposal
We propose to make a dev-container for VS-code with the following features:
1. editing of Ampersand scripts
2. language-specific support, such as syntax colouring.
3. on-the-fly errors (Ampersand daemon)
4. generate a functional specification
5. deploy a prototype (sandbox)
6. generate an atlas.
The intention is to replace RAP by this thing. (We can call it RAP-5)

**Comment by hanjoosten** [comment]
The following `components` are likely to help with this endevour:

- [vscode](https://code.visualstudio.com/docs/editor/vscode-web). This is an instance of vscode that is run in a browser.
- [vscode remote development](https://code.visualstudio.com/docs/remote/remote-overview). I think that this will allow us to define a docker image that has all required features on board
- [The ampersand CLI](https://github.com/AmpersandTarski/Ampersand/releases). The ampersand CLI tool can be run as a daemon. As such, it can validate ADL scripts. Also other Ampersand functionality can be invoked by means of this executable.
- [The `Ampersand (ADL) language support` plugin](https://marketplace.visualstudio.com/items?itemName=AmpersandTarski.language-ampersand). This plugin offers ADL specific code validation. 
- Even more goodies?

**Comment by stefjoosten** [comment]
Let us make a tentative list of requirements

 - [ ] As a user, I want to use Ampersand in the cloud, without any footprint on my laptop, so I can try things out spontaneously.
 - [ ] As a user, I want to make Ampersand prototypes, for demonstration purposes.
 - [ ] As a user, I want to make functional specifications as a document, to kick-start the design of an information system.
 - [ ] As a user, I want to analyse my Ampersand script in an atlas, to enhance my understanding comprehensively.
 - [ ] As a user, I want to generate data models, to complement my conceptual analysis with a useful asset.
 - [ ] As a user, I want to deploy my prototype in the cloud, to facilitate design workshops with users.

 - [ ] As an Ampersand developer, I want to replace RAP by an industry-standard IDE to decrease the amount of maintenance effort in the Ampersand team and to benefit maximally of future enhancements by the community at large.
 - [ ] As an Ampersand developer, I want to have a highly maintainable and reproducible IDE for Ampersand, so that we can focus on Ampersand itself.

**Comment by stefjoosten** [comment]
# To-do list
 - [ ] Change the Ampersand compiler to generate a stand-alone atlas so that the IDE can make a command-line call to the Ampersand compiler.
 - [ ] Update the syntax-dependent coloring to the most recent syntax, to realize a more professional look and feel.
 - [ ] Realize a publishable docker image that lets users run Ampersand from their laptops.
 - [ ] Organize hosting so users can run Ampersand on the internet.
 - [ ] Realize a button in VScode to call the Ampersand compiler so that a user can correct mistakes.
 - [ ] Realize a button in VScode to generate a running prototype from a compilation result so that a user can try out how the prototype behaves.
 - [ ] Realize a button in VScode to generate a deployable image from a compilation result so that a user can deploy the image elsewhere.
 - [ ] Realize a button in VScode to generate a functional specification document from a compilation result so that the user can contribute to a design team.
 - [ ] Realize a button in VScode to generate an atlas so that the user can analyze the script.
 - [ ] ...

**Comment by hanjoosten** [comment]
We don't need a button in VScode to call the Ampersand compiler. The ampersand daemon should run instantly
