### ISSUE TITLE
TODO list for November 2020 release of RAP3

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#61]
This list is a result of checking the progress on RAP3. The defects that really must be fixed are in the first list. Without these, RAP3 will not be released to students. If the box is checked, it means that the requirement is satisfied. The bottom list is necessary items too, but they do not inhibit the release.
## features that inhibit the release
 - [x] reactivate the Atlas, which was available on RAP2, to let students browse through the metamodel of their Ampersand-models.
 - [x] reactivate the Prototype generator, which was available on RAP3, to let students run their prototypes.
 - [x] replace HAproxy by Traefik to get an edge router that can route traffic with services dynamically created and deleted, which is necessary when students generate prototypes.
 - [x] Secured server connection (issue #39). HTTPS must be activated and HTTP deactivated. (test on the server, because it doesn't work on localhost)
 - [x] solve "Violation of rule `identity_Interface`" in the Atlas.
 - [x] issue AmpersandTarski/Ampersand#1118 needs to be resolved.
## non-inhibiting features
 - [x] Update the deployment instructions in README.md, so it is visible in the front page of the RAP repository.
 - [x] Make the enroll demo work. The problem is reported in issue AmpersandTarski/Ampersand#1119. A workaround is to run enroll in debug-mode.
 - [ ] place the message "open prototype" where it belongs.
 - [ ] eliminate the yes/no question that MS-Word asks when the user opens a diagnosis document.
 - [ ] adapt the intro video clip to the new situation
 - [ ] login with Github and LinkedIn
 - [ ] login with SAML2 for single sign-on at the OU and disabling the login administration
 - [ ] monitor disk space (issues #45 and #52)
 - [ ] separately downloadable figures (issue #47)
 - [ ] make a version and a commit-number visible for students and hyperlink to RAP issues, for error reporting by students.
 - [ ] clean up the large number of roles (11 at present)

During the past year, we have improved the language documentation on https://ampersandtarski.gitbook.io/documentation.
We have made the automated release procedure for RAP more reliable and reproducible (on the basis of docker-compose)

**Comment by LloydRutledge** [comment]
Nice to have this prioritized list. I wouldn't necessarily make documentation inhibiting but indeed a priority. The other inhibiting issues seem parallel to the documentation. The Atlas is the most important non-inhibiting feature from the student perspective. Monitoring disk space is the most important behind the scenes.

**Comment by stefjoosten** [comment]
The November release has taken place on October 23rd, 2020.
