### ISSUE TITLE
TODO list for RAP4

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#87]
This list is a reminder for the maintenance team of the things to be done on RAP4. None of these things are inhibiting.

 - [ ] place the message "open prototype" where it belongs.
 - [ ] run a student prototype in secure mode, so the browser warning of an insecure link will disappear.
 - [ ] place the environment variables for the student prototype in an env-file for maintainability's sake.
 - [ ] start the Enroll demo with the administrator role off.
 - [ ] make it impossible for a user to reinstall the RAP4 database.
 - [ ] move 'Open Prototype' (in the create script screen) from the "messages" to the place where it belongs.
 - [ ] show 'Open Prototype' only if the student container exists.
 - [ ] Move the "Register" button from the Login-frame.
 - [ ] Treat the database credentials safely using secrets instead of environment variables.
 - [ ] move the RAP4 installation instructions from the Github main page to Docker hub.
 - [ ] Create a rap4-db image so initialization instructions (now in the deploy instructions) can be automated.
 - [ ] eliminate the yes/no question that MS-Word asks when the user opens a diagnosis document.
 - [] make a video clip to introduce the "new script" screen.
 - [ ] make a video clip to show how to generate a functional specification.
 - [ ] make a video clip to show the atlas.
 - [ ] make a video clip to demonstrate how to run a prototype.
 - [ ] login with Github and LinkedIn
 - [ ] login with SAML2 for single sign-on at the OU and disabling the login administration
 - [ ] monitor disk space (issues #45 and #52)
 - [ ] separately downloadable figures (issue #47)
 - [ ] make a version and a commit-number visible for students and hyperlink to RAP issues, for error reporting by students.
 - [ ] clean up the large number of roles (11 at present)
